### ISSUE TITLE
Enable users to train classifiers from a custom dataset 

### ISSUE THREAD

**Issue by hugcis** [DavidHerel/semantics-preserving-encoder#2]
The goal would be to have a function inside the library from which a user could train fasttext classifiers directly from a custom dataset and have it ready to use as part of SPE.

**Comment by hugcis** [comment]
Alternatively, we could just write a tutorial on the README explaining how to do it. Something like
1. Have your dataset in a file in the fasttext format
2. Use the following fasttext commands to train your classifier
3. Move the classifier to the `spe_classifiers` folder

**Comment by DavidHerel** [comment]
Writing the tutorial on the README sounds great because transforming the dataset to fasttext form and then training the classifier is maybe out of the scope of our library. 
I will modify the README!
